---
      
Sw1:
      hostname: 10.52.4.1
      groups:
            - ios_switches
      data:
        country: usa
        region: north
        state: washington
        coast: west
        vendor: cisco_switch
        asn: 123
        domain: ikea
Sw2:
      hostname: 10.52.4.2
      groups: 
            - ios_switches
      data:
        country: usa
        region: north
        state: minnesota
        vendor: cisco_switch
        asn: 123
        domain: ikea
Sw3:
      hostname: 10.52.4.5
      groups: 
            - eos_switches
      data:
        country: usa
        region: north
        state: new york
        vendor: arista
        asn: 123
        domain: interikea
Rt1:
      hostname: 10.52.4.3
      groups:
            - ios_routers
      data:
        country: usa
        region: south
        state: texas
        vendor: cisco_router
        asn: 123
        domain: ikea
Rt2:
      hostname: 10.52.4.4
      groups:
            - ios_routers
      data:
        country: usa
        region: south
        state: california
        coast: west
        vendor: cisco_router
        asn: 123
        domain: ikea

